name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
     - v*
     - pre-release*
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: echo ${{ github.ref_name }}
    - run: echo ${{ github.ref }}
    - run: echo $GITHUB_REF
    - name: Remocao de arquivos existentes
      run: |
        rm ./android/app/google-services.json
        rm ./ios/firebase_app_id_file.json
        rm ./lib/firebase_options.dart
        
        echo "${{ secrets.FIREBASE_GOOGLE_SERVICE_PRD }}"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > ./android/app/google-services.json
        echo "${{ secrets.FIREBASE_OPTIONS_PRD }}"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > ./lib/firebase_options.dart
        echo "${{ secrets.FIREBASE_APP_ID_FILE_PRD }}"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 -d > ./ios/firebase_app_id_file.json
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.3'
    - run: flutter pub get
    - run: flutter pub run flutter_native_splash:create --path=assets/prd_native_splash.yaml
    - run: flutter pub run flutter_launcher_icons -f assets/prd_launcher_icons.yaml
    - run: flutter build apk --split-per-abi --build-name ${{ github.ref_name }}

    - name: Renomear artefatos
      run: |
        dir
        cd build/app/outputs/apk/release/
        for f in *.apk ; do mv -- "$f" "${{ github.ref_name }}_$f" ; done
        cd ../../../../..

    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN_GIT }}
